### ISSUE TITLE
ParZu preprocessing object

### ISSUE THREAD

**Issue by gnmarten** [hsluytergaethje/speaker_identification#1]
File "/home/gnmarten/Downloads/speaker_identification/pipeline/preprocess.py", line 62, in <module>
    -> list[Sentence]:
TypeError: 'type' object is not subscriptable

Parzu is installed and Path in config.ini

(would really like to use this, help is much appreciated)

**Comment by gnmarten** [comment]
the issue is not related to ParZu, but to Flair

I added
from typing import List

and capitalized (in a number of files) the mentions of list (--> List)

and it seems to work now

**Comment by gnmarten** [comment]
I encounter a problem in the preprocessing script (standard "optimal" sieve settings) when dealing with a custom txt-file (full novel, one sentence per line):
An error has occured:
name 'SPEECH_NOUNS' is not defined
in line 268 it does "populate_word_lists(verb_path, mensch_path, vocative_path)", but not the speech_noun_path (defined in config.ini). 
Any ideas what I am doing wrong or should do?

**Comment by hsluytergaethje** [comment]
Hi, 
thank you for reporting this issue!  
Unfortunately, I can't seem to reproduce it. The speech nouns are not read in the `populate_word _list` function, but with `read_word_list` in `Text.py`. This is called in the indirect and the reported sieve files. 

For testing purposes: Have you tried executing the pipeline with the provided data? E.g. with this command:
` python stwr_speaker_annotation.py -c config.ini ../corpus/sentences/rwk_mkhz_6360-1.xmi.sentences.txt` 

Could you provide some more information on how this error occured? 
How did you call the pipeline?
Did you change the directory structure? 
Could you share the full traceback of the error? 
Thanks!

**Comment by gnmarten** [comment]
thank you for your help. as to the speech nouns, Indeed, nothing's wrong with your (magnificent!) script. 

I got things sorted out by cleaning up my text file (a number of * signs caused the script to throw the error mentioned above). 

Amazing work, I am happy to see the Redewiedergabe efforts put to such good usage.
